In [1]:
import numpy as np

In [2]:
def func1 (x):
    return x**2

In [3]:
def simple_numerical_diff(f, x):
    h = 10e-5

    diff = (f(x + h) - f(x - h)) / (2*h)
    return diff

In [4]:
input_data = 4.0
my_func = func1
simple_numerical_diff(my_func, input_data)

7.999999999999119

In [5]:
my_func

<function __main__.func1>

## gradient 계산기 구현하기
f(X):2x+3xy+y^3

In [6]:
input_weight = [1.0, 2.0]
input_data = np.array(input_weight)

In [7]:
def func2(X):
    x = X[0]
    y = X[1]
    return 2*x + 3*x*y + np.power(y, 3)

In [8]:
func2(input_data)

16.0

In [9]:
def numerical_diff(f, X):
    h = 1e-4
    grad = np.zeros_like(X)

    for idx in range(X.size):
        temp_value = X[idx]
        X[idx] = temp_value + h
        f_f = f(X)

        X[idx] = temp_value - h
        f_b = f(X)

        grad[idx] = (f_f - f_b) / (2*h)
        X[idx] = temp_value

    return grad

In [10]:
f2 = func2
numerical_diff(f2, input_data)

array([ 8.        , 15.00000001])

In [11]:
input_data.size

2

##Matrix Variable의 Gradient값을 구하는 함수
f(X):2x+3xy+y^3

In [468]:
matrix =[[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]]
input_data_mt = np.array(matrix)

In [469]:
input_data_mt

array([[1., 2., 3.],
       [4., 5., 6.]])

In [470]:
def t_numerical_diff(f, X):

    temp_var = X
    
    h = 1e-4
    grad = np.zeros(X.shape)
    i = 0
    j = 0

    rows = X.shape[0]
    columns = X.shape[1]
    
    for row in range(rows):
        for column in range(columns):
            
            target_var = float(temp_var[row,column])
            
            temp_var[row,column] = target_var + h           
            func_val_plus = f(temp_var[row,column])   

            temp_var[row,column] = target_var - h           
            func_val_minus = f(temp_var[row,column])   
            
            grad[row,column] = (func_val_plus - func_val_minus) / (2*h)
            temp_var[row,column] = target_var
            
    return grad

In [471]:
def func3(X):
    x = X
    y = X
    return 2*x + 3*x*y + np.power(y, 3)

In [472]:
func3(input_data_mt)

array([[  6.,  24.,  60.],
       [120., 210., 336.]])

In [473]:
t_numerical_diff(func3, input_data_mt)

array([[ 11.00000001,  26.00000001,  47.00000001],
       [ 74.00000001, 107.00000001, 146.00000001]])

In [452]:
len(input_data_mt[0])

3